### ISSUE TITLE
Is it works?

### ISSUE THREAD

**Issue by yoyurec** [ben-eb/postcss-discard-duplicates#2]
have a lot of duplicated (_overwrited_) properties:
```
.myclass {
    height: 1.875rem;
    line-height: 1.875rem;
    ....lot of styles here
    height: 2.5rem;
    line-height: 2.5rem;
}
```
but they do not processed to
```
.myclass {
    ....lot of styles here
    height: 2.5rem;
    line-height: 2.5rem;
}
```
:cry:

**Comment by ben-eb** [comment]
I would argue that this isn't in the module's scope. What you are talking about is merging of declarations, which is a tricky area because of all the permutations of "valid" or "invalid" fallbacks; this is one such valid use case where properties should not be removed:

```css
.class {
  color: black;
  color: rgba(0, 0, 0, .5);
}
```

I have some early work on this done but it's not really ready; there are a lot of properties that it is missing. Trying to find a way to do this safely is quite challenging. :smile:

What *is* in scope is something like https://github.com/ben-eb/postcss-discard-duplicates/issues/1 where partial duplicates are currently not being discarded.

**Comment by yoyurec** [comment]
oh...i see...
just tried to replace outdated **CSSO** with your **CssNano** and missed *merging of declarations*

**Comment by ben-eb** [comment]
I'm working on it. :smile:

**Comment by yoyurec** [comment]
:bow:
